// Committed replay fixture: a full seeded 4-AI game recorded as an action
// log, for the replay viewer (src/ui/scenes/replay_scene.tsx) and its
// Playwright spec. Replaying these actions through the pure reducer from
// createInitialGameState(seed) + start_game reproduces the exact game and
// reaches the scoring phase, the same record-once/replay-forever property
// tests/test_replay_determinism.mjs relies on.
//
// Same-build fixture: regenerate when the Action schema or reducer behavior
// changes (a differently-behaving reducer may not reach scoring on this
// exact trace). Recipe: node --import tsx _temp_gen_fixture.mjs (mirrors
// tests/test_full_game.mjs's playFullGame, recording each dispatched action).
// Recorded from seed 2026; reaches scoring in round 6.

import type { SavedGame } from "../save_log";

/** A full recorded game for the replay viewer; see this file's header for the recipe. */
export const REPLAY_FIXTURE: SavedGame = {
  buildVersion: "fixture",
  seed: 2026,
  mode: "beginner",
  species: "humanoid",
  relaxedTimer: false,
  speed: 8,
  actions: [
    { type: "claim_plot", playerId: 0, row: 0, col: 4 },
    { type: "claim_plot", playerId: 1, row: 1, col: 4 },
    { type: "claim_plot", playerId: 2, row: 2, col: 7 },
    { type: "claim_plot", playerId: 3, row: 3, col: 4 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 1, row: 0, col: 7 },
    { type: "tick" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 1, row: 1, col: 4 },
    { type: "tick" },
    { type: "gamble", playerId: 1 },
    { type: "buy_mule", playerId: 3 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 3, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 3, row: 3, col: 4 },
    { type: "tick" },
    { type: "buy_mule", playerId: 3 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 3, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 3, row: 4, col: 7 },
    { type: "tick" },
    { type: "gamble", playerId: 3 },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 0, row: 0, col: 4 },
    { type: "tick" },
    { type: "hunt_wampus", playerId: 0 },
    { type: "tick" },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "smithore" },
    { type: "tick" },
    { type: "gamble", playerId: 0 },
    { type: "buy_mule", playerId: 2 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 2, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 2, row: 2, col: 7 },
    { type: "tick" },
    { type: "buy_mule", playerId: 2 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 2, resource: "smithore" },
    { type: "tick" },
    { type: "gamble", playerId: 2 },
    { type: "tick" },
    { type: "set_auction_role", playerId: 3, role: "out" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 2, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 2, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 3, role: "out" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 2, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 3, role: "out" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "claim_plot", playerId: 3, row: 3, col: 8 },
    { type: "claim_plot", playerId: 2, row: 4, col: 0 },
    { type: "claim_plot", playerId: 1, row: 4, col: 3 },
    { type: "claim_plot", playerId: 0, row: 4, col: 4 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "gamble", playerId: 1 },
    { type: "gamble", playerId: 3 },
    { type: "buy_mule", playerId: 2 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 2, resource: "smithore" },
    { type: "tick" },
    { type: "place_mule", playerId: 2, row: 0, col: 2 },
    { type: "tick" },
    { type: "gamble", playerId: 2 },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 0, row: 4, col: 4 },
    { type: "tick" },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "food" },
    { type: "tick" },
    { type: "gamble", playerId: 0 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "claim_plot", playerId: 0, row: 0, col: 0 },
    { type: "claim_plot", playerId: 1, row: 0, col: 1 },
    { type: "claim_plot", playerId: 2, row: 0, col: 5 },
    { type: "claim_plot", playerId: 3, row: 0, col: 6 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "gamble", playerId: 2 },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "crystite" },
    { type: "tick" },
    { type: "place_mule", playerId: 1, row: 0, col: 1 },
    { type: "tick" },
    { type: "gamble", playerId: 1 },
    { type: "gamble", playerId: 3 },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 0, row: 0, col: 0 },
    { type: "tick" },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "food" },
    { type: "tick" },
    { type: "gamble", playerId: 0 },
    { type: "tick" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 2, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 3, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "set_auction_role", playerId: 0, role: "out" },
    { type: "set_auction_role", playerId: 2, role: "out" },
    { type: "set_auction_role", playerId: 3, role: "out" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 0, intent: "hold" },
    { type: "set_auction_intent", playerId: 2, intent: "hold" },
    { type: "set_auction_intent", playerId: 3, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_intent", playerId: 1, intent: "hold" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "set_auction_role", playerId: 1, role: "out" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "claim_plot", playerId: 3, row: 0, col: 8 },
    { type: "claim_plot", playerId: 2, row: 1, col: 0 },
    { type: "claim_plot", playerId: 1, row: 1, col: 3 },
    { type: "claim_plot", playerId: 0, row: 1, col: 5 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 1, row: 1, col: 3 },
    { type: "tick" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "food" },
    { type: "tick" },
    { type: "buy_mule", playerId: 2 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 2, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 2, row: 0, col: 5 },
    { type: "tick" },
    { type: "gamble", playerId: 2 },
    { type: "buy_mule", playerId: 3 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 3, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 3, row: 0, col: 6 },
    { type: "tick" },
    { type: "gamble", playerId: 3 },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 0, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 0, row: 1, col: 5 },
    { type: "tick" },
    { type: "hunt_wampus", playerId: 0 },
    { type: "tick" },
    { type: "buy_mule", playerId: 0 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "claim_plot", playerId: 0, row: 1, col: 7 },
    { type: "claim_plot", playerId: 1, row: 1, col: 8 },
    { type: "claim_plot", playerId: 2, row: 2, col: 0 },
    { type: "claim_plot", playerId: 3, row: 2, col: 1 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "bid_land", playerId: 3 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 1, row: 1, col: 3 },
    { type: "tick" },
    { type: "buy_mule", playerId: 1 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 1, resource: "food" },
    { type: "tick" },
    { type: "gamble", playerId: 3 },
    { type: "buy_mule", playerId: 2 },
    { type: "tick" },
    { type: "outfit_mule", playerId: 2, resource: "food" },
    { type: "tick" },
    { type: "place_mule", playerId: 2, row: 1, col: 0 },
    { type: "tick" },
    { type: "gamble", playerId: 2 },
    { type: "gamble", playerId: 0 },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "claim_plot", playerId: 3, row: 2, col: 5 },
    { type: "claim_plot", playerId: 2, row: 2, col: 6 },
    { type: "claim_plot", playerId: 1, row: 3, col: 0 },
    { type: "claim_plot", playerId: 0, row: 3, col: 1 },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "bid_land", playerId: 2 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 0 },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "bid_land", playerId: 1 },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "tick" },
    { type: "end_land_auction" },
    { type: "gamble", playerId: 0 },
    { type: "gamble", playerId: 2 },
    { type: "gamble", playerId: 3 },
    { type: "gamble", playerId: 1 },
    { type: "tick" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
    { type: "tick" },
    { type: "end_auction" },
  ],
};
